### ISSUE TITLE
unexpected '['

### ISSUE THREAD

**Issue by Ventricule** [distantnative/kirby-oembed#18]
Hello !
I have a php bug when I install oembed, its what it say :
> Parse error: syntax error, unexpected '[' in /home/spectrep/www/newsite/site/plugins/oembed/oembed.php on line 72

PHP is 5.3 and if you need more information lets know.

**Comment by distantnative** [comment]
Does the error disappear when you edit `site/plugins/oembed/oembed.php`and replace around line 72

```php
      $oEmbed = $Essence->embed($text, [
          'thumbnailFormat' => 'maxres'
      ]);
```

with

```
      $oEmbed = $Essence->embed($text, ['thumbnailFormat' => 'maxres']);
```

?

**Comment by Ventricule** [comment]
Nope, but I find the problem : 
As of PHP 5.4.0 a shortened syntax for declaring arrays has been introduced:
`$list = [];`
Before the syntax was : 
`$list = array();`
I will upgrade to 5.4, thats simple.
